# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app
COPY . .
RUN npm ci --ignore-scripts
RUN npm run build

FROM node:lts-alpine AS runtime
WORKDIR /app
# Copy production node_modules including symlinks
COPY --from=builder /app/node_modules ./node_modules
# Copy built supabase server
COPY --from=builder /app/packages/mcp-server-supabase/dist ./dist
# Copy mcp-utils package so symlink resolves
COPY --from=builder /app/packages/mcp-utils ./packages/mcp-utils
ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/transports/stdio.js"]
