# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:22-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY packages/mcp-server-postgrest /app

# Install dependencies and build the project
RUN --mount=type=cache,target=/root/.npm npm install && npm run build

# Use a smaller image for the release
FROM node:22-alpine AS release

# Set the working directory in the container
WORKDIR /app

# Copy compiled output and dependencies from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install production dependencies
RUN npm ci --omit=dev

# Specify the command to run the MCP server
ENTRYPOINT ["node", "dist/stdio.js"]